<a href="https://colab.research.google.com/github/SeeeungJ/PythonProject2024-1/blob/main/%EA%B5%90%ED%86%B5%ED%98%BC%EC%9E%A1%EB%8F%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [183]:
import pandas as pd
traffic=pd.read_excel('TrafficVolume(ZONE).xlsx',header=None)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [184]:
traffic.loc[7,3:]=traffic.loc[8,3:]

In [185]:
traffic.drop(8, inplace=True)

In [186]:
traffic.columns=traffic.loc[7]

In [187]:
traffic.drop(index=range(7), inplace=True)

In [188]:
traffic.drop(7, inplace=True)

In [189]:
traffic.reset_index(drop=True,inplace=True)

In [190]:
traffic = traffic.iloc[:, :28]

In [191]:
traffic

7,ZONE ID,시도,시군구,전일,1시,2시,3시,4시,5시,6시,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,11010000,서울특별시,종로구,71836,1191,966,685,652,1467,2539,...,3932,3749,3633,3629,3645,3552,3222,3151,2950,1826
1,11030000,서울특별시,용산구,99808,1992,1716,1338,1198,1997,3862,...,5301,5206,5011,4432,4081,4250,4813,4902,4289,3162
2,11040000,서울특별시,성동구,74527,1206,1053,785,796,1426,2743,...,4199,4235,4210,3885,3558,3386,3387,3420,3001,1944
3,11050000,서울특별시,광진구,67175,888,698,519,544,958,2057,...,3809,3972,4020,3928,3567,3349,3076,2877,2442,1415
4,11060000,서울특별시,동대문구,52104,917,736,510,541,1248,2363,...,2793,2883,2992,2750,2382,2232,2162,2168,1755,1200
5,11070000,서울특별시,중랑구,49526,777,683,481,517,948,2085,...,2674,2738,2808,2684,2431,2166,2033,1922,1647,1125
6,11080000,서울특별시,성북구,56770,900,739,562,607,1093,2294,...,3005,3016,3015,2992,2835,2684,2539,2471,2183,1486
7,11100000,서울특별시,도봉구,60559,998,728,508,636,1504,2920,...,3288,3255,3514,3256,3022,2775,2567,2268,1492,1133
8,11110000,서울특별시,노원구,55740,854,773,577,646,1146,2462,...,3068,3081,3145,3127,2905,2573,2232,2026,1787,1263
9,11130000,서울특별시,서대문구,71631,1116,931,648,628,1329,2754,...,3857,3866,3816,3683,3539,3427,3267,3190,2929,1645
10,11140000,서울특별시,마포구,88063,1592,1464,1086,1031,1745,3526,...,4670,4606,4546,4347,4208,4091,4218,4062,3632,2460
11,11150000,서울특별시,양천구,91795,1733,1402,1122,1254,2733,4055,...,4554,4742,4862,4919,5171,4984,5009,4228,2920,2543
12,11160000,서울특별시,강서구,69117,862,797,611,743,1556,3008,...,3780,3797,3841,3767,3670,3318,2935,2599,2182,1353
13,11170000,서울특별시,구로구,5621,35,30,16,18,29,88,...,291,353,486,723,521,159,134,109,58,60
14,11180000,서울특별시,금천구,39144,357,321,243,332,623,1316,...,2084,2115,2151,2448,2357,1958,1560,1297,1004,676
15,11190000,서울특별시,영등포구,67047,966,873,700,727,1439,2784,...,3545,3498,3437,3553,3137,2960,2858,2723,2468,1694
16,11200000,서울특별시,동작구,89194,1544,1493,1089,1123,2012,3591,...,4946,4759,4519,4096,3758,3699,4050,4124,3577,2539
17,11210000,서울특별시,관악구,46372,356,321,243,234,461,1129,...,2597,2727,3066,3332,2894,2482,1888,1522,1280,817
18,11220000,서울특별시,서초구,70594,1094,979,776,839,1722,2885,...,3670,3746,3808,3774,3582,3313,3139,3139,2550,1763
19,11230000,서울특별시,강남구,77642,1345,1173,867,812,1432,2850,...,4203,4083,3950,3795,3604,3438,3594,3527,3086,2059
20,11240000,서울특별시,송파구,83171,923,821,640,776,1714,3343,...,4702,4862,4836,4565,4256,3850,3536,3137,2453,1449
21,11250000,서울특별시,강동구,91689,881,745,615,823,1946,3443,...,5327,5321,5240,5022,4792,4394,3914,3230,2450,1481

In [192]:
jung=pd.DataFrame([{
    'ZONE ID': '11020000',
    '시도': '서울특별시',
    '시군구': '중구',
    '전일':(traffic.iloc[0:3,3].astype('int').sum()+traffic.iloc[9:11,3].astype('int').sum())/5,
    '1시':(traffic.iloc[0:3,4].astype('int').sum()+traffic.iloc[9:11,4].astype('int').sum())/5,
    '2시':(traffic.iloc[0:3,5].astype('int').sum()+traffic.iloc[9:11,5].astype('int').sum())/5,
    '3시':(traffic.iloc[0:3,6].astype('int').sum()+traffic.iloc[9:11,6].astype('int').sum())/5,
    '4시':(traffic.iloc[0:3,7].astype('int').sum()+traffic.iloc[9:11,7].astype('int').sum())/5,
    '5시':(traffic.iloc[0:3,8].astype('int').sum()+traffic.iloc[9:11,8].astype('int').sum())/5,
    '6시':(traffic.iloc[0:3,9].astype('int').sum()+traffic.iloc[9:11,9].astype('int').sum())/5,
    '7시':(traffic.iloc[0:3,10].astype('int').sum()+traffic.iloc[9:11,10].astype('int').sum())/5,
    '8시':(traffic.iloc[0:3,11].astype('int').sum()+traffic.iloc[9:11,11].astype('int').sum())/5,
    '9시':(traffic.iloc[0:3,12].astype('int').sum()+traffic.iloc[9:11,12].astype('int').sum())/5,
    '10시':(traffic.iloc[0:3,13].astype('int').sum()+traffic.iloc[9:11,13].astype('int').sum())/5,
    '11시':(traffic.iloc[0:3,14].astype('int').sum()+traffic.iloc[9:11,14].astype('int').sum())/5,
    '12시':(traffic.iloc[0:3,15].astype('int').sum()+traffic.iloc[9:11,15].astype('int').sum())/5,
    '13시':(traffic.iloc[0:3,16].astype('int').sum()+traffic.iloc[9:11,16].astype('int').sum())/5,
    '14시':(traffic.iloc[0:3,17].astype('int').sum()+traffic.iloc[9:11,17].astype('int').sum())/5,
    '15시':(traffic.iloc[0:3,18].astype('int').sum()+traffic.iloc[9:11,18].astype('int').sum())/5,
    '16시':(traffic.iloc[0:3,19].astype('int').sum()+traffic.iloc[9:11,19].astype('int').sum())/5,
    '17시':(traffic.iloc[0:3,20].astype('int').sum()+traffic.iloc[9:11,20].astype('int').sum())/5,
    '18시':(traffic.iloc[0:3,21].astype('int').sum()+traffic.iloc[9:11,21].astype('int').sum())/5,
    '19시':(traffic.iloc[0:3,22].astype('int').sum()+traffic.iloc[9:11,22].astype('int').sum())/5,
    '20시':(traffic.iloc[0:3,23].astype('int').sum()+traffic.iloc[9:11,23].astype('int').sum())/5,
    '21시':(traffic.iloc[0:3,24].astype('int').sum()+traffic.iloc[9:11,24].astype('int').sum())/5,
    '22시':(traffic.iloc[0:3,25].astype('int').sum()+traffic.iloc[9:11,25].astype('int').sum())/5,
    '23시':(traffic.iloc[0:3,26].astype('int').sum()+traffic.iloc[9:11,26].astype('int').sum())/5,
    '24시':(traffic.iloc[0:3,27].astype('int').sum()+traffic.iloc[9:11,27].astype('int').sum())/5
}])

In [193]:
jung

,ZONE ID,시도,시군구,전일,1시,2시,3시,4시,5시,6시,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,11020000,서울특별시,중구,81173.0,1419.4,1226.0,908.4,861.0,1592.8,3084.8,...,4391.8,4332.4,4243.2,3995.2,3806.2,3741.2,3781.4,3745.0,3360.2,2207.4

In [194]:
gangbuk=pd.DataFrame([{
    'ZONE ID': '11090000',
    '시도': '서울특별시',
    '시군구': '강북구',
    '전일':traffic.iloc[6:9,3].astype('int').sum()/3,
    '1시':traffic.iloc[6:9,4].astype('int').sum()/3,
    '2시':traffic.iloc[6:9,5].astype('int').sum()/3,
    '3시':traffic.iloc[6:9,6].astype('int').sum()/3,
    '4시':traffic.iloc[6:9,7].astype('int').sum()/3,
    '5시':traffic.iloc[6:9,8].astype('int').sum()/3,
    '6시':traffic.iloc[6:9,9].astype('int').sum()/3,
    '7시':traffic.iloc[6:9,10].astype('int').sum()/3,
    '8시':traffic.iloc[6:9,11].astype('int').sum()/3,
    '9시':traffic.iloc[6:9,12].astype('int').sum()/3,
    '10시':traffic.iloc[6:9,13].astype('int').sum()/3,
    '11시':traffic.iloc[6:9,14].astype('int').sum()/3,
    '12시':traffic.iloc[6:9,15].astype('int').sum()/3,
    '13시':traffic.iloc[6:9,16].astype('int').sum()/3,
    '14시':traffic.iloc[6:9,17].astype('int').sum()/3,
    '15시':traffic.iloc[6:9,18].astype('int').sum()/3,
    '16시':traffic.iloc[6:9,19].astype('int').sum()/3,
    '17시':traffic.iloc[6:9,20].astype('int').sum()/3,
    '18시':traffic.iloc[6:9,21].astype('int').sum()/3,
    '19시':traffic.iloc[6:9,22].astype('int').sum()/3,
    '20시':traffic.iloc[6:9,23].astype('int').sum()/3,
    '21시':traffic.iloc[6:9,24].astype('int').sum()/3,
    '22시':traffic.iloc[6:9,25].astype('int').sum()/3,
    '23시':traffic.iloc[6:9,26].astype('int').sum()/3,
    '24시':traffic.iloc[6:9,27].astype('int').sum()/3
}])

In [195]:
gangbuk

,ZONE ID,시도,시군구,전일,1시,2시,3시,4시,5시,6시,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,11090000,서울특별시,강북구,57689.666667,917.333333,746.666667,549.0,629.666667,1247.666667,2558.666667,...,3120.333333,3117.333333,3224.666667,3125.0,2920.666667,2677.333333,2446.0,2255.0,1820.666667,1294.0

In [196]:
ep=pd.DataFrame([{
    'ZONE ID': '11120000',
    '시도': '서울특별시',
    '시군구': '은평구',
    '전일':(int(traffic.iloc[0,3])+traffic.iloc[9:11,3].astype('int').sum())/5,
    '1시':(int(traffic.iloc[0,4])+traffic.iloc[9:11,4].astype('int').sum())/5,
    '2시':(int(traffic.iloc[0,5])+traffic.iloc[9:11,5].astype('int').sum())/5,
    '3시':(int(traffic.iloc[0,6])+traffic.iloc[9:11,6].astype('int').sum())/5,
    '4시':(int(traffic.iloc[0,7])+traffic.iloc[9:11,7].astype('int').sum())/5,
    '5시':(int(traffic.iloc[0,8])+traffic.iloc[9:11,8].astype('int').sum())/5,
    '6시':(int(traffic.iloc[0,9])+traffic.iloc[9:11,9].astype('int').sum())/5,
    '7시':(int(traffic.iloc[0,10])+traffic.iloc[9:11,10].astype('int').sum())/5,
    '8시':(int(traffic.iloc[0,11])+traffic.iloc[9:11,11].astype('int').sum())/5,
    '9시':(int(traffic.iloc[0,12])+traffic.iloc[9:11,12].astype('int').sum())/5,
    '10시':(int(traffic.iloc[0,13])+traffic.iloc[9:11,13].astype('int').sum())/5,
    '11시':(int(traffic.iloc[0,14])+traffic.iloc[9:11,14].astype('int').sum())/5,
    '12시':(int(traffic.iloc[0,15])+traffic.iloc[9:11,15].astype('int').sum())/5,
    '13시':(int(traffic.iloc[0,16])+traffic.iloc[9:11,16].astype('int').sum())/5,
    '14시':(int(traffic.iloc[0,17])+traffic.iloc[9:11,17].astype('int').sum())/5,
    '15시':(int(traffic.iloc[0,18])+traffic.iloc[9:11,18].astype('int').sum())/5,
    '16시':(int(traffic.iloc[0,19])+traffic.iloc[9:11,19].astype('int').sum())/5,
    '17시':(int(traffic.iloc[0,20])+traffic.iloc[9:11,20].astype('int').sum())/5,
    '18시':(int(traffic.iloc[0,21])+traffic.iloc[9:11,21].astype('int').sum())/5,
    '19시':(int(traffic.iloc[0,22])+traffic.iloc[9:11,22].astype('int').sum())/5,
    '20시':(int(traffic.iloc[0,23])+traffic.iloc[9:11,23].astype('int').sum())/5,
    '21시':(int(traffic.iloc[0,24])+traffic.iloc[9:11,24].astype('int').sum())/5,
    '22시':(int(traffic.iloc[0,25])+traffic.iloc[9:11,25].astype('int').sum())/5,
    '23시':(int(traffic.iloc[0,26])+traffic.iloc[9:11,26].astype('int').sum())/5,
    '24시':(int(traffic.iloc[0,27])+traffic.iloc[9:11,27].astype('int').sum())/5
}])

In [197]:
ep

,ZONE ID,시도,시군구,전일,1시,2시,3시,4시,5시,6시,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,11120000,서울특별시,은평구,46306.0,779.8,672.2,483.8,462.2,908.2,1763.8,...,2491.8,2444.2,2399.0,2331.8,2278.4,2214.0,2141.4,2080.6,1902.2,1186.2

In [198]:
traffic = pd.concat([traffic, jung, gangbuk, ep], ignore_index=True)

In [199]:
traffic

,ZONE ID,시도,시군구,전일,1시,2시,3시,4시,5시,6시,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,11010000,서울특별시,종로구,71836,1191,966,685,652,1467,2539,...,3932,3749,3633,3629,3645,3552,3222,3151,2950,1826
1,11030000,서울특별시,용산구,99808,1992,1716,1338,1198,1997,3862,...,5301,5206,5011,4432,4081,4250,4813,4902,4289,3162
2,11040000,서울특별시,성동구,74527,1206,1053,785,796,1426,2743,...,4199,4235,4210,3885,3558,3386,3387,3420,3001,1944
3,11050000,서울특별시,광진구,67175,888,698,519,544,958,2057,...,3809,3972,4020,3928,3567,3349,3076,2877,2442,1415
4,11060000,서울특별시,동대문구,52104,917,736,510,541,1248,2363,...,2793,2883,2992,2750,2382,2232,2162,2168,1755,1200
5,11070000,서울특별시,중랑구,49526,777,683,481,517,948,2085,...,2674,2738,2808,2684,2431,2166,2033,1922,1647,1125
6,11080000,서울특별시,성북구,56770,900,739,562,607,1093,2294,...,3005,3016,3015,2992,2835,2684,2539,2471,2183,1486
7,11100000,서울특별시,도봉구,60559,998,728,508,636,1504,2920,...,3288,3255,3514,3256,3022,2775,2567,2268,1492,1133
8,11110000,서울특별시,노원구,55740,854,773,577,646,1146,2462,...,3068,3081,3145,3127,2905,2573,2232,2026,1787,1263
9,11130000,서울특별시,서대문구,71631,1116,931,648,628,1329,2754,...,3857,3866,3816,3683,3539,3427,3267,3190,2929,1645
10,11140000,서울특별시,마포구,88063,1592,1464,1086,1031,1745,3526,...,4670,4606,4546,4347,4208,4091,4218,4062,3632,2460
11,11150000,서울특별시,양천구,91795,1733,1402,1122,1254,2733,4055,...,4554,4742,4862,4919,5171,4984,5009,4228,2920,2543
12,11160000,서울특별시,강서구,69117,862,797,611,743,1556,3008,...,3780,3797,3841,3767,3670,3318,2935,2599,2182,1353
13,11170000,서울특별시,구로구,5621,35,30,16,18,29,88,...,291,353,486,723,521,159,134,109,58,60
14,11180000,서울특별시,금천구,39144,357,321,243,332,623,1316,...,2084,2115,2151,2448,2357,1958,1560,1297,1004,676
15,11190000,서울특별시,영등포구,67047,966,873,700,727,1439,2784,...,3545,3498,3437,3553,3137,2960,2858,2723,2468,1694
16,11200000,서울특별시,동작구,89194,1544,1493,1089,1123,2012,3591,...,4946,4759,4519,4096,3758,3699,4050,4124,3577,2539
17,11210000,서울특별시,관악구,46372,356,321,243,234,461,1129,...,2597,2727,3066,3332,2894,2482,1888,1522,1280,817
18,11220000,서울특별시,서초구,70594,1094,979,776,839,1722,2885,...,3670,3746,3808,3774,3582,3313,3139,3139,2550,1763
19,11230000,서울특별시,강남구,77642,1345,1173,867,812,1432,2850,...,4203,4083,3950,3795,3604,3438,3594,3527,3086,2059
20,11240000,서울특별시,송파구,83171,923,821,640,776,1714,3343,...,4702,4862,4836,4565,4256,3850,3536,3137,2453,1449
21,11250000,서울특별시,강동구,91689,881,745,615,823,1946,3443,...,5327,5321,5240,5022,4792,4394,3914,3230,2450,1481
22,11020000,서울특별시,중구,81173.0,1419.4,1226.0,908.4,861.0,1592.8,3084.8,...,4391.8,4332.4,4243.2,3995.2,3806.2,3741.2,3781.4,3745.0,3360.2,2207.4
23,11090000,서울특별시,강북구,57689.666667,917.333333,746.666667,549.0,629.666667,1247.666667,2558.666667,...,3120.333333,3117.333333,3224.666667,3125.0,2920.666667,2677.333333,2446.0,2255.0,1820.666667,1294.0
24,11120000,서울특별시,은평구,46306.0,779.8,672.2,483.8,462.2,908.2,1763.8,...,2491.8,2444.2,2399.0,2331.8,2278.4,2214.0,2141.4,2080.6,1902.2,1186.2